import '../models/collection_products.dart';

List<Product> getProducts() {
  return [
    Product(
      name: 'Midnight Dreams',
      description: 'A surreal depiction of a city skyline under moonlight.',
      price: 1200,
      category: 'Surrealism',
      stockQuantity: 3,
      createdAt: DateTime(2025, 1, 15),
      image: 'assets/art.jpg',
      width: 40,
      length: 60,
    ),
    Product(
      name: 'Golden Valley',
      description: 'Rolling hills bathed in golden sunlight.',
      price: 95.50,
      category: 'Landscape',
      stockQuantity: 5,
      createdAt: DateTime(2025, 2, 5),
      image: 'assets/art.jpg',
      width: 50,
      length: 70,
    ),
    Product(
      name: 'The Abstract Truth',
      description: 'Bold colors and expressive forms, pure abstraction.',
      price: 1400,
      category: 'Abstract',
      stockQuantity: 2,
      createdAt: DateTime(2025, 3, 8),
      image: 'assets/art.jpg',
      width: 45,
      length: 65,
    ),
    Product(
      name: 'Digital Bloom',
      description: 'A cyberpunk-inspired flower in neon.',
      price: 850,
      category: 'Digital Art',
      stockQuantity: 4,
      createdAt: DateTime(2025, 1, 20),
      image: 'assets/art.jpg',
      width: 35,
      length: 55,
    ),
    Product(
      name: 'Echoes of Silence',
      description: 'Muted tones of a forest cloaked in fog.',
      price: 1050,
      category: 'Nature',
      stockQuantity: 6,
      createdAt: DateTime(2025, 2, 12),
      image: 'assets/art.jpg',
      width: 50,
      length: 75,
    ),
    Product(
      name: 'The Last Dance',
      description: 'Abstract motion of two dancers caught in time.',
      price: 1150,
      category: 'Modern',
      stockQuantity: 2,
      createdAt: DateTime(2025, 3, 2),
      image: 'assets/art.jpg',
      width: 60,
      length: 80,
    ),
    Product(
      name: 'Neon Samurai',
      description: 'Futuristic warrior in glowing armor.',
      price: 1500,
      category: 'Sci-Fi',
      stockQuantity: 1,
      createdAt: DateTime(2025, 2, 28),
      image: 'assets/art.jpg',
      width: 55,
      length: 85,
    ),
    Product(
      name: 'Minimal Bloom',
      description: 'A single line sketch of a rose on beige.',
      price: 700,
      category: 'Minimalist',
      stockQuantity: 10,
      createdAt: DateTime(2025, 1, 10),
      image: 'assets/art.jpg',
      width: 30,
      length: 45,
    ),
    Product(
      name: 'Pixel Sunset',
      description: 'Retro pixel art of a beach sunset.',
      price: 600,
      category: 'Pixel Art',
      stockQuantity: 7,
      createdAt: DateTime(2025, 3, 18),
      image: 'assets/art.jpg',
      width: 40,
      length: 40,
    ),
    Product(
      name: 'Fragmented Reality',
      description: 'A face shattered into mirrored reflections.',
      price: 1100,
      category: 'Expressionism',
      stockQuantity: 3,
      createdAt: DateTime(2025, 2, 22),
      image: 'assets/art.jpg',
      width: 48,
      length: 68,
    ),
    Product(
      name: 'Dreamwalker',
      description: 'Mystical figure drifting through a cosmic void.',
      price: 1350,
      category: 'Fantasy',
      stockQuantity: 2,
      createdAt: DateTime(2025, 1, 30),
      image: 'assets/art.jpg',
      width: 52,
      length: 72,
    ),
    Product(
      name: 'Glass Horizon',
      description: 'Abstract reflection of clouds on a glassy lake.',
      price: 980,
      category: 'Abstract Landscape',
      stockQuantity: 5,
      createdAt: DateTime(2025, 3, 12),
      image: 'assets/art.jpg',
      width: 58,
      length: 78,
    ),
    Product(
      name: 'Urban Poetry',
      description: 'Graffiti-inspired piece with layered messages.',
      price: 890,
      category: 'Street Art',
      stockQuantity: 4,
      createdAt: DateTime(2025, 2, 17),
      image: 'assets/art.jpg',
      width: 36,
      length: 60,
    ),
    Product(
      name: 'Through the Veil',
      description: 'Haunting depiction of a ghostly figure.',
      price: 1080,
      category: 'Gothic',
      stockQuantity: 3,
      createdAt: DateTime(2025, 3, 5),
      image: 'assets/art.jpg',
      width: 50,
      length: 70,
    ),
    Product(
      name: 'Harmony in Chaos',
      description: 'Controlled brushstrokes in a storm of colors.',
      price: 1300,
      category: 'Contemporary',
      stockQuantity: 3,
      createdAt: DateTime(2025, 1, 25),
      image: 'assets/art.jpg',
      width: 44,
      length: 64,
    ),
    Product(
      name: 'Ink & Idea',
      description: 'Monochrome sketch showing raw imagination.',
      price: 750,
      category: 'Sketch',
      stockQuantity: 8,
      createdAt: DateTime(2025, 3, 10),
      image: 'assets/art.jpg',
      width: 38,
      length: 55,
    ),
  ];
}